// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.22.3
// source: sng-story.proto

package snggcc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characters   []*Character   `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	Locations    []*Location    `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	Passages     []*Passage     `protobuf:"bytes,3,rep,name=passages,proto3" json:"passages,omitempty"`
	Environments []*Environment `protobuf:"bytes,4,rep,name=environments,proto3" json:"environments,omitempty"`
	Actions      []*Action      `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Dialogues    []*Dialogue    `protobuf:"bytes,6,rep,name=dialogues,proto3" json:"dialogues,omitempty"`
	Stories      []*Story       `protobuf:"bytes,7,rep,name=stories,proto3" json:"stories,omitempty"`
}

func (x *ScriptPart) Reset() {
	*x = ScriptPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptPart) ProtoMessage() {}

func (x *ScriptPart) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptPart.ProtoReflect.Descriptor instead.
func (*ScriptPart) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptPart) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *ScriptPart) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *ScriptPart) GetPassages() []*Passage {
	if x != nil {
		return x.Passages
	}
	return nil
}

func (x *ScriptPart) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *ScriptPart) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ScriptPart) GetDialogues() []*Dialogue {
	if x != nil {
		return x.Dialogues
	}
	return nil
}

func (x *ScriptPart) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

type OptionalString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string     `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	When *LuaScript `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalString) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OptionalString) GetWhen() *LuaScript {
	if x != nil {
		return x.When
	}
	return nil
}

type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description []*OptionalString `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	Player      bool              `protobuf:"varint,4,opt,name=player,proto3" json:"player,omitempty"`
	Tags        []*OptionalString `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Actions     []*Action         `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Stats       []*CharacterStat  `protobuf:"bytes,7,rep,name=stats,proto3" json:"stats,omitempty"`
	Items       []*Item           `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{2}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetDescription() []*OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Character) GetPlayer() bool {
	if x != nil {
		return x.Player
	}
	return false
}

func (x *Character) GetTags() []*OptionalString {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Character) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Character) GetStats() []*CharacterStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Character) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CharacterRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CharacterRef) Reset() {
	*x = CharacterRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterRef) ProtoMessage() {}

func (x *CharacterRef) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterRef.ProtoReflect.Descriptor instead.
func (*CharacterRef) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Story struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartPassage *Passage     `protobuf:"bytes,2,opt,name=startPassage,proto3" json:"startPassage,omitempty"`
	Characters   []*Character `protobuf:"bytes,3,rep,name=characters,proto3" json:"characters,omitempty"`
}

func (x *Story) Reset() {
	*x = Story{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{4}
}

func (x *Story) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Story) GetStartPassage() *Passage {
	if x != nil {
		return x.StartPassage
	}
	return nil
}

func (x *Story) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type Passage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location     *Location       `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Characters   []*CharacterRef `protobuf:"bytes,4,rep,name=characters,proto3" json:"characters,omitempty"`
	Environments []*Environment  `protobuf:"bytes,5,rep,name=environments,proto3" json:"environments,omitempty"`
	Items        []*Item         `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Passage) Reset() {
	*x = Passage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Passage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passage) ProtoMessage() {}

func (x *Passage) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passage.ProtoReflect.Descriptor instead.
func (*Passage) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{5}
}

func (x *Passage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Passage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Passage) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Passage) GetCharacters() []*CharacterRef {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *Passage) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *Passage) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Environment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description []*OptionalString `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	Actions     []*Action         `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Flags       []string          `protobuf:"bytes,5,rep,name=flags,proto3" json:"flags,omitempty"`
	When        *LuaScript        `protobuf:"bytes,6,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *Environment) Reset() {
	*x = Environment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{6}
}

func (x *Environment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetDescription() []*OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Environment) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Environment) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Environment) GetWhen() *LuaScript {
	if x != nil {
		return x.When
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description []*OptionalString `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	Actions     []*Action         `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Count       int32             `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Price       int32             `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	When        *LuaScript        `protobuf:"bytes,7,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{7}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() []*OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Item) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetWhen() *LuaScript {
	if x != nil {
		return x.When
	}
	return nil
}

type LuaScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
}

func (x *LuaScript) Reset() {
	*x = LuaScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LuaScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuaScript) ProtoMessage() {}

func (x *LuaScript) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuaScript.ProtoReflect.Descriptor instead.
func (*LuaScript) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{8}
}

func (x *LuaScript) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text            string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Description     []*OptionalString      `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	Tags            []*OptionalString      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	PassageID       string                 `protobuf:"bytes,5,opt,name=passageID,proto3" json:"passageID,omitempty"`
	Dialogue        *Dialogue              `protobuf:"bytes,6,opt,name=dialogue,proto3" json:"dialogue,omitempty"`
	Script          *LuaScript             `protobuf:"bytes,7,opt,name=script,proto3" json:"script,omitempty"`
	When            *LuaScript             `protobuf:"bytes,8,opt,name=when,proto3" json:"when,omitempty"`
	CharacterFilter *CharacterActionFilter `protobuf:"bytes,9,opt,name=characterFilter,proto3" json:"characterFilter,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{9}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Action) GetDescription() []*OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Action) GetTags() []*OptionalString {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Action) GetPassageID() string {
	if x != nil {
		return x.PassageID
	}
	return ""
}

func (x *Action) GetDialogue() *Dialogue {
	if x != nil {
		return x.Dialogue
	}
	return nil
}

func (x *Action) GetScript() *LuaScript {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *Action) GetWhen() *LuaScript {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *Action) GetCharacterFilter() *CharacterActionFilter {
	if x != nil {
		return x.CharacterFilter
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description []*OptionalString `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	When        *LuaScript        `protobuf:"bytes,4,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{10}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetDescription() []*OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Location) GetWhen() *LuaScript {
	if x != nil {
		return x.When
	}
	return nil
}

type DialogueLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterRef string          `protobuf:"bytes,2,opt,name=CharacterRef,proto3" json:"CharacterRef,omitempty"`
	Text         string          `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Answers      []*DialogueLine `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	ScriptBefore *LuaScript      `protobuf:"bytes,5,opt,name=script_before,json=scriptBefore,proto3" json:"script_before,omitempty"`
	ScriptAfter  *LuaScript      `protobuf:"bytes,6,opt,name=script_after,json=scriptAfter,proto3" json:"script_after,omitempty"`
	When         *LuaScript      `protobuf:"bytes,7,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *DialogueLine) Reset() {
	*x = DialogueLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogueLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueLine) ProtoMessage() {}

func (x *DialogueLine) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueLine.ProtoReflect.Descriptor instead.
func (*DialogueLine) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{11}
}

func (x *DialogueLine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DialogueLine) GetCharacterRef() string {
	if x != nil {
		return x.CharacterRef
	}
	return ""
}

func (x *DialogueLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DialogueLine) GetAnswers() []*DialogueLine {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DialogueLine) GetScriptBefore() *LuaScript {
	if x != nil {
		return x.ScriptBefore
	}
	return nil
}

func (x *DialogueLine) GetScriptAfter() *LuaScript {
	if x != nil {
		return x.ScriptAfter
	}
	return nil
}

func (x *DialogueLine) GetWhen() *LuaScript {
	if x != nil {
		return x.When
	}
	return nil
}

type Dialogue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lines []*DialogueLine `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
}

func (x *Dialogue) Reset() {
	*x = Dialogue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dialogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dialogue) ProtoMessage() {}

func (x *Dialogue) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dialogue.ProtoReflect.Descriptor instead.
func (*Dialogue) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{12}
}

func (x *Dialogue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dialogue) GetLines() []*DialogueLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type CharacterStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//
	//	*CharacterStat_IntValue
	//	*CharacterStat_FloatValue
	//	*CharacterStat_BoolValue
	Value isCharacterStat_Value `protobuf_oneof:"value"`
}

func (x *CharacterStat) Reset() {
	*x = CharacterStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStat) ProtoMessage() {}

func (x *CharacterStat) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStat.ProtoReflect.Descriptor instead.
func (*CharacterStat) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{13}
}

func (x *CharacterStat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CharacterStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *CharacterStat) GetValue() isCharacterStat_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CharacterStat) GetIntValue() int64 {
	if x, ok := x.GetValue().(*CharacterStat_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *CharacterStat) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*CharacterStat_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *CharacterStat) GetBoolValue() bool {
	if x, ok := x.GetValue().(*CharacterStat_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

type isCharacterStat_Value interface {
	isCharacterStat_Value()
}

type CharacterStat_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=intValue,proto3,oneof"`
}

type CharacterStat_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=floatValue,proto3,oneof"`
}

type CharacterStat_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=boolValue,proto3,oneof"`
}

func (*CharacterStat_IntValue) isCharacterStat_Value() {}

func (*CharacterStat_FloatValue) isCharacterStat_Value() {}

func (*CharacterStat_BoolValue) isCharacterStat_Value() {}

type CharacterActionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *LuaScript `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *CharacterActionFilter) Reset() {
	*x = CharacterActionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sng_story_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterActionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterActionFilter) ProtoMessage() {}

func (x *CharacterActionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sng_story_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterActionFilter.ProtoReflect.Descriptor instead.
func (*CharacterActionFilter) Descriptor() ([]byte, []int) {
	return file_sng_story_proto_rawDescGZIP(), []int{14}
}

func (x *CharacterActionFilter) GetFilter() *LuaScript {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_sng_story_proto protoreflect.FileDescriptor

var file_sng_story_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6e, 0x67, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x73, 0x6e, 0x67, 0x22, 0xc3, 0x02, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0c,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x64, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73,
	0x6e, 0x67, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x09, 0x64, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x0e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x99, 0x02, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x25, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x79, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x0c, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x22, 0xe2, 0x01,
	0x0a, 0x07, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73,
	0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x66, 0x52,
	0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0c, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0xc9, 0x01, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6e,
	0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x77, 0x68,
	0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c,
	0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0xd8,
	0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x1d, 0x0a, 0x09, 0x4c, 0x75, 0x61,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x22, 0xe7, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65,
	0x12, 0x26, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x75, 0x61,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x12, 0x44, 0x0a, 0x0f,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x77, 0x68,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c,
	0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x8f,
	0x02, 0x0a, 0x0c, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x73, 0x12, 0x33, 0x0a, 0x0d, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x62,
	0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e,
	0x67, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x0c, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52,
	0x0b, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04,
	0x77, 0x68, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6e, 0x67,
	0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e,
	0x22, 0x43, 0x0a, 0x08, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6e,
	0x67, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52,
	0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x62,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x26, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x73, 0x6e, 0x67, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x72, 0x62, 0x79, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x6e,
	0x67, 0x67, 0x63, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sng_story_proto_rawDescOnce sync.Once
	file_sng_story_proto_rawDescData = file_sng_story_proto_rawDesc
)

func file_sng_story_proto_rawDescGZIP() []byte {
	file_sng_story_proto_rawDescOnce.Do(func() {
		file_sng_story_proto_rawDescData = protoimpl.X.CompressGZIP(file_sng_story_proto_rawDescData)
	})
	return file_sng_story_proto_rawDescData
}

var file_sng_story_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sng_story_proto_goTypes = []any{
	(*ScriptPart)(nil),            // 0: sng.ScriptPart
	(*OptionalString)(nil),        // 1: sng.OptionalString
	(*Character)(nil),             // 2: sng.Character
	(*CharacterRef)(nil),          // 3: sng.CharacterRef
	(*Story)(nil),                 // 4: sng.Story
	(*Passage)(nil),               // 5: sng.Passage
	(*Environment)(nil),           // 6: sng.Environment
	(*Item)(nil),                  // 7: sng.Item
	(*LuaScript)(nil),             // 8: sng.LuaScript
	(*Action)(nil),                // 9: sng.Action
	(*Location)(nil),              // 10: sng.Location
	(*DialogueLine)(nil),          // 11: sng.DialogueLine
	(*Dialogue)(nil),              // 12: sng.Dialogue
	(*CharacterStat)(nil),         // 13: sng.CharacterStat
	(*CharacterActionFilter)(nil), // 14: sng.CharacterActionFilter
}
var file_sng_story_proto_depIdxs = []int32{
	2,  // 0: sng.ScriptPart.characters:type_name -> sng.Character
	10, // 1: sng.ScriptPart.locations:type_name -> sng.Location
	5,  // 2: sng.ScriptPart.passages:type_name -> sng.Passage
	6,  // 3: sng.ScriptPart.environments:type_name -> sng.Environment
	9,  // 4: sng.ScriptPart.actions:type_name -> sng.Action
	12, // 5: sng.ScriptPart.dialogues:type_name -> sng.Dialogue
	4,  // 6: sng.ScriptPart.stories:type_name -> sng.Story
	8,  // 7: sng.OptionalString.when:type_name -> sng.LuaScript
	1,  // 8: sng.Character.description:type_name -> sng.OptionalString
	1,  // 9: sng.Character.tags:type_name -> sng.OptionalString
	9,  // 10: sng.Character.actions:type_name -> sng.Action
	13, // 11: sng.Character.stats:type_name -> sng.CharacterStat
	7,  // 12: sng.Character.items:type_name -> sng.Item
	5,  // 13: sng.Story.startPassage:type_name -> sng.Passage
	2,  // 14: sng.Story.characters:type_name -> sng.Character
	10, // 15: sng.Passage.location:type_name -> sng.Location
	3,  // 16: sng.Passage.characters:type_name -> sng.CharacterRef
	6,  // 17: sng.Passage.environments:type_name -> sng.Environment
	7,  // 18: sng.Passage.items:type_name -> sng.Item
	1,  // 19: sng.Environment.description:type_name -> sng.OptionalString
	9,  // 20: sng.Environment.actions:type_name -> sng.Action
	8,  // 21: sng.Environment.when:type_name -> sng.LuaScript
	1,  // 22: sng.Item.description:type_name -> sng.OptionalString
	9,  // 23: sng.Item.actions:type_name -> sng.Action
	8,  // 24: sng.Item.when:type_name -> sng.LuaScript
	1,  // 25: sng.Action.description:type_name -> sng.OptionalString
	1,  // 26: sng.Action.tags:type_name -> sng.OptionalString
	12, // 27: sng.Action.dialogue:type_name -> sng.Dialogue
	8,  // 28: sng.Action.script:type_name -> sng.LuaScript
	8,  // 29: sng.Action.when:type_name -> sng.LuaScript
	14, // 30: sng.Action.characterFilter:type_name -> sng.CharacterActionFilter
	1,  // 31: sng.Location.description:type_name -> sng.OptionalString
	8,  // 32: sng.Location.when:type_name -> sng.LuaScript
	11, // 33: sng.DialogueLine.answers:type_name -> sng.DialogueLine
	8,  // 34: sng.DialogueLine.script_before:type_name -> sng.LuaScript
	8,  // 35: sng.DialogueLine.script_after:type_name -> sng.LuaScript
	8,  // 36: sng.DialogueLine.when:type_name -> sng.LuaScript
	11, // 37: sng.Dialogue.lines:type_name -> sng.DialogueLine
	8,  // 38: sng.CharacterActionFilter.filter:type_name -> sng.LuaScript
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_sng_story_proto_init() }
func file_sng_story_proto_init() {
	if File_sng_story_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sng_story_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ScriptPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OptionalString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Story); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Passage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Environment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LuaScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DialogueLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Dialogue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sng_story_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterActionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sng_story_proto_msgTypes[13].OneofWrappers = []any{
		(*CharacterStat_IntValue)(nil),
		(*CharacterStat_FloatValue)(nil),
		(*CharacterStat_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sng_story_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sng_story_proto_goTypes,
		DependencyIndexes: file_sng_story_proto_depIdxs,
		MessageInfos:      file_sng_story_proto_msgTypes,
	}.Build()
	File_sng_story_proto = out.File
	file_sng_story_proto_rawDesc = nil
	file_sng_story_proto_goTypes = nil
	file_sng_story_proto_depIdxs = nil
}
